version: 2
environment:
  BUILD_NUM: $CIRCLE_BUILD_NUM
jobs:
  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: make test || true
  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: make build
      - run: make deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
